; Song Ouagadougou in Lightweight format.
; Generated by Arkos Tracker 2.

Ouagadougou_SongStart:
	defb "ATLW"	; Format marker (LightWeight).
	defb 0	; Format version.
	defw Ouagadougou_FmInstrumentTable
	defw Ouagadougou_ArpeggioTable
	defw Ouagadougou_PitchTable
; Table of the Subsongs.
	defw Ouagadougou_Subsong0

; The Arpeggio table.
Ouagadougou_ArpeggioTable:
	defw 0

; The Pitch table.
Ouagadougou_PitchTable:
	defw 0

; The FM Instrument table.
Ouagadougou_FmInstrumentTable:
	defw Ouagadougou_FmInstrument0
	defw Ouagadougou_FmInstrument1
	defw Ouagadougou_FmInstrument2

Ouagadougou_FmInstrument0:
	defb 255	; Speed.

Ouagadougou_FmInstrument0_Loop:	defb 0	; Volume: 0.

	defb 4	; End the instrument.
	defw Ouagadougou_FmInstrument0_Loop	; Loops.

Ouagadougou_FmInstrument1:
	defb 0	; Speed.

	defb 189	; Volume: 15.
	defb 25	; Arpeggio: 12.
	defb 11	; Noise: 11.

	defb 185	; Volume: 14.
	defb 27	; Arpeggio: 13.
	defb 10	; Noise: 10.

	defb 181	; Volume: 13.
	defb 33	; Arpeggio: 16.
	defb 9	; Noise: 9.

	defb 181	; Volume: 13.
	defb 19	; Arpeggio: 9.
	defb 8	; Noise: 8.

	defb 177	; Volume: 12.
	defb 1	; Arpeggio: 0.
	defb 7	; Noise: 7.

	defb 169	; Volume: 10.
	defb 19	; Arpeggio: 9.
	defb 6	; Noise: 6.

	defb 161	; Volume: 8.
	defb 29	; Arpeggio: 14.
	defb 5	; Noise: 5.

	defb 153	; Volume: 6.
	defb 1	; Arpeggio: 0.
	defb 4	; Noise: 4.

	defb 145	; Volume: 4.
	defb 1	; Arpeggio: 0.
	defb 3	; Noise: 3.

	defb 141	; Volume: 3.
	defb 1	; Arpeggio: 0.
	defb 2	; Noise: 2.

	defb 4	; End the instrument.
	defw Ouagadougou_FmInstrument0_Loop	; Loop to silence.

Ouagadougou_FmInstrument2:
	defb 0	; Speed.

	defb 61	; Volume: 15.

	defb 57	; Volume: 14.

	defb 53	; Volume: 13.

	defb 49	; Volume: 12.

	defb 45	; Volume: 11.

Ouagadougou_FmInstrument2_Loop:	defb 41	; Volume: 10.

	defb 4	; End the instrument.
	defw Ouagadougou_FmInstrument2_Loop	; Loops.

; Song Ouagadougou, Subsong 0 - Main - in Lightweight format.
; Generated by Arkos Tracker 2.

Ouagadougou_Subsong0:
; The Linker.
; Pattern 0
Ouagadougou_Subsong0_Loop:
	defb 15	; State byte.
	defb 4	; New speed.
	defb 63	; New height.
	defb 0, 0, 0	; The transpositions.
	defw Ouagadougou_Subsong0_Track0, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 1
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track5, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 2
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track0, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 3
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track7, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 4
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track3, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 5
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track6, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 6
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track3, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 7
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track9, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 8
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track4, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 9
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track8, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 10
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track4, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 11
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track10, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 12
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track21, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 13
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track0, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 14
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track5, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 15
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track0, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 16
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track7, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 17
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track11, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 18
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track12, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 19
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track11, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 20
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track13, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 21
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track14, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 22
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track15, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 23
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track14, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 24
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track16, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 25
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track17, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 26
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track18, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 27
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track17, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

; Pattern 28
	defb 1	; State byte.
	defw Ouagadougou_Subsong0_Track19, Ouagadougou_Subsong0_Track1, Ouagadougou_Subsong0_Track2	; The tracks.

	defb 0	; End of the subsong.
	defw Ouagadougou_Subsong0_Loop

; The Tracks.
Ouagadougou_Subsong0_Track0:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 61, 6	; Long wait: 7.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 190	; Short wait: 3.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 63, 19	; Escaped note: 19.
	defb 61, 6	; Long wait: 7.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 191, 19	; Escaped note: 19.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 190	; Short wait: 3.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track1:
	defb 61, 63	; Long wait: 64.


Ouagadougou_Subsong0_Track2:
	defb 61, 63	; Long wait: 64.


Ouagadougou_Subsong0_Track3:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 29	; Note: 53.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 190	; Short wait: 3.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 62	; Short wait: 1.

	defb 33	; Note: 57.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 27	; Note: 51.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 29	; Note: 53.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track4:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 77	; Escaped note: 77.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 63, 79	; Escaped note: 79.
	defb 29	; Note: 53.
	defb 63, 77	; Escaped note: 77.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 63, 72	; Escaped note: 72.
	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 63, 75	; Escaped note: 75.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 46	; Note: 70.
	defb 63, 72	; Escaped note: 72.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 75	; Escaped note: 75.
	defb 4	; New instrument: 2.
	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 63, 72	; Escaped note: 72.
	defb 36	; Note: 60.
	defb 46	; Note: 70.
	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 63, 72	; Escaped note: 72.
	defb 33	; Note: 57.
	defb 43	; Note: 67.
	defb 34	; Note: 58.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 46	; Note: 70.
	defb 63, 19	; Escaped note: 19.
	defb 63, 72	; Escaped note: 72.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 27	; Note: 51.
	defb 63, 75	; Escaped note: 75.
	defb 63, 19	; Escaped note: 19.
	defb 63, 72	; Escaped note: 72.
	defb 29	; Note: 53.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 75	; Escaped note: 75.
	defb 4	; New instrument: 2.
	defb 3	; Note: 27.
	defb 43	; Note: 67.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track5:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 61, 6	; Long wait: 7.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 190	; Short wait: 3.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 3	; Note: 27.
	defb 61, 4	; Long wait: 5.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 190	; Short wait: 3.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 19	; Escaped note: 19.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 190	; Short wait: 3.


Ouagadougou_Subsong0_Track6:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 29	; Note: 53.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 190	; Short wait: 3.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 29	; Note: 53.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 162	; Note: 58.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track7:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 61, 6	; Long wait: 7.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 140	; Note: 36.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 190	; Short wait: 3.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 190	; Short wait: 3.

	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 3	; Note: 27.
	defb 61, 4	; Long wait: 5.

	defb 3	; Note: 27.
	defb 190	; Short wait: 3.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 190	; Short wait: 3.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track8:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 77	; Escaped note: 77.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 63, 79	; Escaped note: 79.
	defb 29	; Note: 53.
	defb 63, 77	; Escaped note: 77.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 63, 72	; Escaped note: 72.
	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 63, 79	; Escaped note: 79.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 63, 77	; Escaped note: 77.
	defb 63, 72	; Escaped note: 72.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 31	; Note: 55.
	defb 63, 77	; Escaped note: 77.
	defb 0	; Note: 24.
	defb 63, 72	; Escaped note: 72.
	defb 31	; Note: 55.
	defb 46	; Note: 70.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 63, 72	; Escaped note: 72.
	defb 39	; Note: 63.
	defb 41	; Note: 65.
	defb 43	; Note: 67.
	defb 43	; Note: 67.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 46	; Note: 70.
	defb 7	; Note: 31.
	defb 63, 72	; Escaped note: 72.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 29	; Note: 53.
	defb 63, 75	; Escaped note: 75.
	defb 63, 19	; Escaped note: 19.
	defb 63, 72	; Escaped note: 72.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 75	; Escaped note: 75.
	defb 4	; New instrument: 2.
	defb 34	; Note: 58.
	defb 43	; Note: 67.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track9:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 29	; Note: 53.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 190	; Short wait: 3.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 152	; Note: 48.
	defb 0	; New instrument: 0.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track10:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 77	; Escaped note: 77.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 63, 79	; Escaped note: 79.
	defb 29	; Note: 53.
	defb 63, 77	; Escaped note: 77.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 159	; Note: 55.
	defb 4	; New instrument: 2.
	defb 63, 72	; Escaped note: 72.
	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 63, 79	; Escaped note: 79.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 63, 77	; Escaped note: 77.
	defb 63, 72	; Escaped note: 72.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 31	; Note: 55.
	defb 63, 77	; Escaped note: 77.
	defb 0	; Note: 24.
	defb 63, 72	; Escaped note: 72.
	defb 31	; Note: 55.
	defb 46	; Note: 70.
	defb 3	; Note: 27.
	defb 61, 14	; Long wait: 15.

	defb 63, 22	; Escaped note: 22.
	defb 61, 6	; Long wait: 7.

	defb 63, 19	; Escaped note: 19.
	defb 61, 6	; Long wait: 7.


Ouagadougou_Subsong0_Track11:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 167	; Note: 63.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 171	; Note: 67.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 164	; Note: 60.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track12:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 19	; Escaped note: 19.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track13:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 131	; Note: 27.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 46	; Note: 70.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track14:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 31	; Note: 55.
	defb 63, 79	; Escaped note: 79.
	defb 36	; Note: 60.
	defb 63, 77	; Escaped note: 77.
	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 167	; Note: 63.
	defb 4	; New instrument: 2.
	defb 63, 75	; Escaped note: 75.
	defb 12	; Note: 36.
	defb 63, 77	; Escaped note: 77.
	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 63, 82	; Escaped note: 82.
	defb 63, 22	; Escaped note: 22.
	defb 63, 79	; Escaped note: 79.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 43	; Note: 67.
	defb 63, 79	; Escaped note: 79.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 63, 79	; Escaped note: 79.
	defb 63, 19	; Escaped note: 19.
	defb 62	; Short wait: 1.

	defb 36	; Note: 60.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 164	; Note: 60.
	defb 4	; New instrument: 2.
	defb 63, 77	; Escaped note: 77.
	defb 63, 19	; Escaped note: 19.
	defb 63, 79	; Escaped note: 79.
	defb 63, 19	; Escaped note: 19.
	defb 63, 82	; Escaped note: 82.
	defb 63, 22	; Escaped note: 22.
	defb 63, 79	; Escaped note: 79.
	defb 31	; Note: 55.
	defb 62	; Short wait: 1.

	defb 63, 19	; Escaped note: 19.
	defb 63, 77	; Escaped note: 77.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 3	; Note: 27.
	defb 63, 75	; Escaped note: 75.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track15:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 63, 79	; Escaped note: 79.
	defb 43	; Note: 67.
	defb 63, 82	; Escaped note: 82.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 63, 84	; Escaped note: 84.
	defb 12	; Note: 36.
	defb 62	; Short wait: 1.

	defb 10	; Note: 34.
	defb 63, 84	; Escaped note: 84.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 63, 82	; Escaped note: 82.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 63, 79	; Escaped note: 79.
	defb 41	; Note: 65.
	defb 63, 82	; Escaped note: 82.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 62	; Short wait: 1.

	defb 34	; Note: 58.
	defb 63, 82	; Escaped note: 82.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 63, 77	; Escaped note: 77.
	defb 63, 22	; Escaped note: 22.
	defb 63, 79	; Escaped note: 79.
	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 41	; Note: 65.
	defb 63, 79	; Escaped note: 79.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 63, 19	; Escaped note: 19.
	defb 63, 82	; Escaped note: 82.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 63, 79	; Escaped note: 79.
	defb 63, 77	; Escaped note: 77.

Ouagadougou_Subsong0_Track16:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 63, 84	; Escaped note: 84.
	defb 43	; Note: 67.
	defb 63, 82	; Escaped note: 82.
	defb 41	; Note: 65.
	defb 63, 79	; Escaped note: 79.
	defb 43	; Note: 67.
	defb 63, 82	; Escaped note: 82.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 12	; Note: 36.
	defb 63, 79	; Escaped note: 79.
	defb 10	; Note: 34.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 63, 82	; Escaped note: 82.
	defb 63, 22	; Escaped note: 22.
	defb 63, 79	; Escaped note: 79.
	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 63, 77	; Escaped note: 77.
	defb 0	; Note: 24.
	defb 63, 79	; Escaped note: 79.
	defb 41	; Note: 65.
	defb 62	; Short wait: 1.

	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 39	; Note: 63.
	defb 63, 82	; Escaped note: 82.
	defb 41	; Note: 65.
	defb 63, 79	; Escaped note: 79.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 63, 84	; Escaped note: 84.
	defb 63, 82	; Escaped note: 82.
	defb 3	; Note: 27.
	defb 63, 79	; Escaped note: 79.
	defb 3	; Note: 27.
	defb 62	; Short wait: 1.

	defb 7	; Note: 31.
	defb 63, 77	; Escaped note: 77.
	defb 63, 22	; Escaped note: 22.
	defb 62	; Short wait: 1.

	defb 46	; Note: 70.
	defb 63, 79	; Escaped note: 79.
	defb 43	; Note: 67.
	defb 62	; Short wait: 1.

	defb 63, 22	; Escaped note: 22.
	defb 63, 84	; Escaped note: 84.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 82	; Escaped note: 82.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.

Ouagadougou_Subsong0_Track17:
	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 63, 82	; Escaped note: 82.
	defb 63, 79	; Escaped note: 79.
	defb 63, 82	; Escaped note: 82.
	defb 62	; Short wait: 1.

	defb 63, 79	; Escaped note: 79.
	defb 63, 77	; Escaped note: 77.
	defb 63, 79	; Escaped note: 79.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 63, 75	; Escaped note: 75.
	defb 63, 77	; Escaped note: 77.
	defb 254	; Short wait: 4.

	defb 63, 72	; Escaped note: 72.
	defb 63, 75	; Escaped note: 75.
	defb 63, 77	; Escaped note: 77.
	defb 63, 79	; Escaped note: 79.
	defb 254	; Short wait: 4.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 63, 82	; Escaped note: 82.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 63, 79	; Escaped note: 79.
	defb 63, 84	; Escaped note: 84.
	defb 63, 82	; Escaped note: 82.
	defb 126	; Short wait: 2.

	defb 63, 79	; Escaped note: 79.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.

	defb 191, 82	; Escaped note: 82.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 17	; Note: 41.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track18:
	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 63, 87	; Escaped note: 87.
	defb 63, 79	; Escaped note: 79.
	defb 63, 82	; Escaped note: 82.
	defb 126	; Short wait: 2.

	defb 63, 79	; Escaped note: 79.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 77	; Escaped note: 77.
	defb 4	; New instrument: 2.
	defb 63, 79	; Escaped note: 79.
	defb 190	; Short wait: 3.

	defb 63, 82	; Escaped note: 82.
	defb 190	; Short wait: 3.

	defb 63, 84	; Escaped note: 84.
	defb 126	; Short wait: 2.

	defb 63, 87	; Escaped note: 87.
	defb 63, 84	; Escaped note: 84.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 82	; Escaped note: 82.
	defb 4	; New instrument: 2.
	defb 63, 84	; Escaped note: 84.
	defb 126	; Short wait: 2.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 63, 75	; Escaped note: 75.
	defb 63, 77	; Escaped note: 77.
	defb 63, 79	; Escaped note: 79.
	defb 126	; Short wait: 2.

	defb 63, 82	; Escaped note: 82.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 63, 82	; Escaped note: 82.
	defb 63, 79	; Escaped note: 79.
	defb 62	; Short wait: 1.

	defb 63, 82	; Escaped note: 82.
	defb 190	; Short wait: 3.

	defb 63, 79	; Escaped note: 79.
	defb 62	; Short wait: 1.

	defb 63, 77	; Escaped note: 77.
	defb 62	; Short wait: 1.

	defb 63, 75	; Escaped note: 75.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 62	; Short wait: 1.

	defb 63, 72	; Escaped note: 72.
	defb 62	; Short wait: 1.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track19:
	defb 191, 82	; Escaped note: 82.
	defb 4	; New instrument: 2.
	defb 63, 84	; Escaped note: 84.
	defb 63, 87	; Escaped note: 87.
	defb 63, 84	; Escaped note: 84.
	defb 63, 82	; Escaped note: 82.
	defb 63, 84	; Escaped note: 84.
	defb 126	; Short wait: 2.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 87	; Escaped note: 87.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 89	; Escaped note: 89.
	defb 4	; New instrument: 2.
	defb 190	; Short wait: 3.

	defb 63, 91	; Escaped note: 91.
	defb 190	; Short wait: 3.

	defb 63, 89	; Escaped note: 89.
	defb 63, 87	; Escaped note: 87.
	defb 63, 84	; Escaped note: 84.
	defb 126	; Short wait: 2.

	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 82	; Escaped note: 82.
	defb 4	; New instrument: 2.
	defb 63, 84	; Escaped note: 84.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 126	; Short wait: 2.

	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 63, 82	; Escaped note: 82.
	defb 62	; Short wait: 1.

	defb 63, 87	; Escaped note: 87.
	defb 63, 84	; Escaped note: 84.
	defb 62	; Short wait: 1.

	defb 63, 79	; Escaped note: 79.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 79	; Escaped note: 79.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 82	; Escaped note: 82.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 84	; Escaped note: 84.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 191, 75	; Escaped note: 75.
	defb 4	; New instrument: 2.
	defb 63, 72	; Escaped note: 72.
	defb 62	; Short wait: 1.

	defb 46	; Note: 70.
	defb 63, 72	; Escaped note: 72.
	defb 0	; Note: 24.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 171	; Note: 67.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 174	; Note: 70.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 191, 72	; Escaped note: 72.
	defb 4	; New instrument: 2.
	defb 145	; Note: 41.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.


Ouagadougou_Subsong0_Track21:
	defb 128	; Note: 24.
	defb 4	; New instrument: 2.
	defb 61, 30	; Long wait: 31.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 62	; Short wait: 1.

	defb 0	; Note: 24.
	defb 61, 16	; Long wait: 17.

	defb 130	; Note: 26.
	defb 2	; New instrument: 1.
	defb 62	; Short wait: 1.

	defb 63, 15	; Escaped note: 15.
	defb 62	; Short wait: 1.

	defb 63, 2	; Escaped note: 2.
	defb 63, 2	; Escaped note: 2.
	defb 63, 2	; Escaped note: 2.
	defb 190	; Short wait: 3.


